// This file is generated by Firebase Studio.

'use server';

/**
 * @fileOverview A maintenance schedule suggestion AI agent.
 *
 * - suggestMaintenanceSchedule - A function that handles the maintenance schedule suggestion process.
 * - SuggestMaintenanceScheduleInput - The input type for the suggestMaintenanceSchedule function.
 * - SuggestMaintenanceScheduleOutput - The return type for the suggestMaintenanceSchedule function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestMaintenanceScheduleInputSchema = z.object({
  vehicleUsage: z
    .string()
    .describe('Description of the vehicle usage patterns, including mileage, load, and operating conditions.'),
  serviceHistory: z
    .string()
    .describe('Detailed service history of the vehicle, including dates, types of service, and parts replaced.'),
  serviceParameters: z
    .string()
    .describe(
      'Parameters of the service such as periodicity in months, periodicity in km, and default supplier.'
    ),
});
export type SuggestMaintenanceScheduleInput = z.infer<typeof SuggestMaintenanceScheduleInputSchema>;

const SuggestMaintenanceScheduleOutputSchema = z.object({
  suggestedSchedule: z
    .string()
    .describe(
      'A detailed maintenance schedule with suggested dates and types of service, optimized for the vehicle usage and service history.'
    ),
  rationale: z
    .string()
    .describe(
      'Explanation of why the suggested schedule is optimal, considering the vehicle usage patterns and service history.'
    ),
});
export type SuggestMaintenanceScheduleOutput = z.infer<
  typeof SuggestMaintenanceScheduleOutputSchema
>;

export async function suggestMaintenanceSchedule(
  input: SuggestMaintenanceScheduleInput
): Promise<SuggestMaintenanceScheduleOutput> {
  return suggestMaintenanceScheduleFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestMaintenanceSchedulePrompt',
  input: {schema: SuggestMaintenanceScheduleInputSchema},
  output: {schema: SuggestMaintenanceScheduleOutputSchema},
  prompt: `You are an expert in fleet maintenance, specializing in creating optimal maintenance schedules.

  Based on the vehicle usage patterns, service history, and service parameters, suggest a maintenance schedule that minimizes downtime and maximizes vehicle lifespan.

  Vehicle Usage: {{{vehicleUsage}}}
  Service History: {{{serviceHistory}}}
  Service Parameters: {{{serviceParameters}}}
  `,
});

const suggestMaintenanceScheduleFlow = ai.defineFlow(
  {
    name: 'suggestMaintenanceScheduleFlow',
    inputSchema: SuggestMaintenanceScheduleInputSchema,
    outputSchema: SuggestMaintenanceScheduleOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
