// This file is the single source of truth for mock data.
// It is used by the database seeder to populate Firestore.

import { parse } from 'date-fns';
import type {
  Category,
  Service,
  Vehicle,
  RawVehicleService,
  CategoryID,
} from './types';


export const CATEGORIES: Category[] = [
  { id: 'LOGISTICO', name: 'Logístico', order: 0 },
  { id: 'EMPILHADEIRAS', name: 'Empilhadeiras', order: 1 },
  { id: 'PASSEIO', name: 'Passeio', order: 2 },
  { id: 'MOTOS', name: 'Motos', order: 3 },
  { id: 'GERADORES', name: 'Geradores', order: 4 },
];

export const VEHICLES: Vehicle[] = [
  { id: 'v1', plate: 'ONC 9390', category: 'LOGISTICO', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v1/600/400' },
  { id: 'v2', plate: 'PQT 1H75', category: 'LOGISTICO', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v2/600/400' },
  { id: 'v3', plate: 'RBU 9C38', category: 'LOGISTICO', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v3/600/400' },
  { id: 'v4', plate: 'RCB 0E98', category: 'LOGISTICO', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v4/600/400' },
  { id: 'v5', plate: 'SCX 0J04', category: 'LOGISTICO', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v5/600/400' },
  { id: 'v6', plate: 'SCP 5J36', category: 'LOGISTICO', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v6/600/400' },
  { id: 'v7', plate: 'OGS 8583', category: 'LOGISTICO', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v7/600/400' },
  { id: 'v8', plate: 'ONC 9190', category: 'LOGISTICO', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v8/600/400' },
  { id: 'v9', plate: 'RBS 5E06', category: 'LOGISTICO', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v9/600/400' },
  { id: 'v10', plate: 'NWO 8655', category: 'LOGISTICO', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v10/600/400' },
  { id: 'v11', plate: 'OGS 8G13', category: 'LOGISTICO', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v11/600/400' },
  { id: 'v12', plate: 'PQH 4780', category: 'LOGISTICO', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v12/600/400' },
  { id: 'v13', plate: 'SCY 3I97', category: 'LOGISTICO', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v13/600/400' },
  { id: 'v14', plate: 'PQE 3070', category: 'LOGISTICO', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v14/600/400' },
  { id: 'v15', plate: 'NVO 8161', category: 'LOGISTICO', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v15/600/400' },
  { id: 'v16', plate: 'HYSTER 60XT - 182', category: 'EMPILHADEIRAS', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v16/600/400' },
  { id: 'v17', plate: 'HYSTER 60FT - 75', category: 'EMPILHADEIRAS', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v17/600/400' },
  { id: 'v18', plate: 'HYSTER 60XT - 168', category: 'EMPILHADEIRAS', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v18/600/400' },
  { id: 'v19', plate: 'HYSTER 55XM - 76', category: 'EMPILHADEIRAS', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v19/600/400' },
  { id: 'v20', plate: 'CLARK GTS30 - 132', category: 'EMPILHADEIRAS', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v20/600/400' },
  { id: 'v21', plate: 'TLC30 DIESEL - 179', category: 'EMPILHADEIRAS', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v21/600/400' },
  { id: 'v22', plate: 'STILL FMX17 - 153', category: 'EMPILHADEIRAS', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v22/600/400' },
  { id: 'v23', plate: 'STILL FMX17 - 154', category: 'EMPILHADEIRAS', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v23/600/400' },
  { id: 'v24', plate: 'CLARK C30 - 108', category: 'EMPILHADEIRAS', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v24/600/400' },
  { id: 'v25', plate: 'STILL EGV16 - 161', category: 'EMPILHADEIRAS', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v25/600/400' },
  { id: 'v26', plate: 'HYSTER 60XT - 181', category: 'EMPILHADEIRAS', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v26/600/400' },
  { id: 'v27', plate: 'CLARK C30 - 122', category: 'EMPILHADEIRAS', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v27/600/400' },
  { id: 'v28', plate: 'STILL EGV16 - 165', category: 'EMPILHADEIRAS', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v28/600/400' },
  { id: 'v29', plate: 'PQR 3H80', category: 'PASSEIO', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v29/600/400' },
  { id: 'v30', plate: 'RBO 1C73', category: 'PASSEIO', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v30/600/400' },
  { id: 'v31', plate: 'RBO 1C93', category: 'PASSEIO', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v31/600/400' },
  { id: 'v32', plate: 'SCN 5C62', category: 'PASSEIO', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v32/600/400' },
  { id: 'v33', plate: 'SCH 3I62', category: 'PASSEIO', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v33/600/400' },
  { id: 'v34', plate: 'PQE 9370', category: 'PASSEIO', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v34/600/400' },
  { id: 'v35', plate: 'SDC 3A35', category: 'PASSEIO', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v35/600/400' },
  { id: 'v36', plate: 'SCQ 2H05', category: 'PASSEIO', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v36/600/400' },
  { id: 'v37', plate: 'SDL 3D58', category: 'PASSEIO', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v37/600/400' },
  { id: 'v38', plate: 'SDN 3G91', category: 'PASSEIO', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v38/600/400' },
  { id: 'v39', plate: 'ONC 9390', category: 'MOTOS', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v39/600/400' },
  { id: 'v40', plate: 'PQT 1H75', category: 'MOTOS', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v40/600/400' },
  { id: 'v41', plate: 'RBU 9C38', category: 'MOTOS', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v41/600/400' },
  { id: 'v42', plate: 'RCB 0E98', category: 'MOTOS', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v42/600/400' },
  { id: 'v43', plate: 'SCX 0J04', category: 'MOTOS', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v43/600/400' },
  { id: 'v44', plate: 'SCP 5J36', category: 'MOTOS', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v44/600/400' },
  { id: 'v45', plate: 'OGS 8583', category: 'MOTOS', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v45/600/400' },
  { id: 'v46', plate: 'ONC 9190', category: 'MOTOS', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v46/600/400' },
  { id: 'v47', plate: 'RBS 5E06', category: 'MOTOS', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v47/600/400' },
  { id: 'v48', plate: 'NWO 8655', category: 'MOTOS', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v48/600/400' },
  { id: 'v49', plate: 'OGS 8G13', category: 'MOTOS', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v49/600/400' },
  { id: 'v50', plate: 'PQH 4780', category: 'MOTOS', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v50/600/400' },
  { id: 'v51', plate: 'SCY 3I97', category: 'MOTOS', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v51/600/400' },
  { id: 'v52', plate: 'PQE 3070', category: 'MOTOS', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v52/600/400' },
  { id: 'v53', plate: 'NVO 8161', category: 'MOTOS', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v53/600/400' },
  { id: 'v54', plate: '86 - MATRIZ', category: 'GERADORES', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v54/600/400' },
  { id: 'v55', plate: '111 - CD', category: 'GERADORES', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v55/600/400' },
  { id: 'v56', plate: '87 - CATEDRAL', category: 'GERADORES', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v56/600/400' },
  { id: 'v57', plate: '112 - MINEIROS', category: 'GERADORES', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v57/600/400' },
  { id: 'v58', plate: '148 - RHARO', category: 'GERADORES', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v58/600/400' },
  { id: 'v59', plate: '162 - SAID ABDALLA', category: 'GERADORES', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v59/600/400' },
  { id: 'v60', plate: '98 - RIO VERDE', category: 'GERADORES', currentKm: 0, active: true, photoUrl: 'https://picsum.photos/seed/v60/600/400' },
];

export const SERVICES: Service[] = [
  { id: 's1', name: 'Óleo do motor', categoryId: 'LOGISTICO', order: 0 },
  { id: 's2', name: 'Filtro de diesel', categoryId: 'LOGISTICO', order: 1 },
  { id: 's3', name: 'Filtro separador de água', categoryId: 'LOGISTICO', order: 2 },
  { id: 's4', name: 'Filtro de arla', categoryId: 'LOGISTICO', order: 3 },
  { id: 's5', name: 'Óleo do câmbio', categoryId: 'LOGISTICO', order: 4 },
  { id: 's6', name: 'Óleo do diferencial', categoryId: 'LOGISTICO', order: 5 },
  { id: 's7', name: 'Revisão do sistema de arla', categoryId: 'LOGISTICO', order: 6 },
  { id: 's8', name: 'Rodizio de baterias', categoryId: 'LOGISTICO', order: 7 },
  { id: 's9', name: 'Lubrificação', categoryId: 'LOGISTICO', order: 8 },
  { id: 's10', name: 'Extintor', categoryId: 'LOGISTICO', order: 9 },
  { id: 's11', name: 'Revisão da suspensão, cubos, rodas e freios', categoryId: 'LOGISTICO', order: 10 },
  { id: 's12', name: 'Radiador, intercooler e bloco do motor', categoryId: 'LOGISTICO', order: 11 },
  { id: 's13', name: 'Tacógrafo', categoryId: 'LOGISTICO', order: 12 },
  { id: 's14', name: 'Alinhamento', categoryId: 'LOGISTICO', order: 13 },
  { id: 's15', name: 'Regulagem de válvulas', categoryId: 'LOGISTICO', order: 14 },
  { id: 's16', name: 'Óleo do motor e filtros', categoryId: 'PASSEIO', order: 0 },
  { id: 's17', name: 'Óleo da transmissão', categoryId: 'PASSEIO', order: 1 },
  { id: 's18', name: 'Óleo do motor PSI', categoryId: 'EMPILHADEIRAS', order: 0 },
  { id: 's19', name: 'Óleo hidraulico', categoryId: 'EMPILHADEIRAS', order: 1 },
  { id: 's20', name: 'Correia dentada', categoryId: 'EMPILHADEIRAS', order: 2 },
  { id: 's21', name: 'Pneus traseiros', categoryId: 'EMPILHADEIRAS', order: 3 },
  { id: 's22', name: 'Bateria', categoryId: 'EMPILHADEIRAS', order: 4 },
  { id: 's23', name: 'Revisão periódica', categoryId: 'MOTOS', order: 0 },
  { id: 's24', name: 'Revisão', categoryId: 'GERADORES', order: 0 },
];

// Omit the status, nextDate, and nextKm fields, as they will be calculated dynamically.
// Also, convert Date objects to strings for Firestore compatibility.
export const VEHICLE_SERVICES_RAW: Omit<RawVehicleService, 'id'> & { id: string }[] = [
    { id: 'vs1', vehicleId: 'v1', serviceId: 's1', lastDate: parse('03/06/2025', 'dd/MM/yyyy', new Date()).toISOString(), lastKm: 392365, supplier: 'Interno', responsible: 'Admin', km: 20000, months: 12 },
    { id: 'vs2', vehicleId: 'v1', serviceId: 's2', lastDate: parse('03/06/2025', 'dd/MM/yyyy', new Date()).toISOString(), lastKm: 392365, supplier: 'Interno', responsible: 'Admin', km: 10000, months: 6 },
    { id: 'vs3', vehicleId: 'v1', serviceId: 's3', lastDate: parse('03/06/2025', 'dd/MM/yyyy', new Date()).toISOString(), lastKm: 392365, supplier: 'Interno', responsible: 'Admin', km: 10000, months: 6 },
    { id: 'vs4', vehicleId: 'v1', serviceId: 's4', lastDate: parse('09/09/2025', 'dd/MM/yyyy', new Date()).toISOString(), lastKm: 404995, supplier: 'CHIP TRUCK', responsible: 'Admin', km: 40000, months: 18 },
    { id: 'vs5', vehicleId: 'v1', serviceId: 's5', lastDate: parse('20/08/2024', 'dd/MM/yyyy', new Date()).toISOString(), lastKm: 380000, supplier: 'DANIEL', responsible: 'Admin', km: 60000, months: 18 },
    { id: 'vs6', vehicleId: 'v1', serviceId: 's6', lastDate: parse('20/08/2024', 'dd/MM/yyyy', new Date()).toISOString(), lastKm: 380000, supplier: 'DANIEL', responsible: 'Admin', km: 60000, months: 18 },
    { id: 'vs7', vehicleId: 'v1', serviceId: 's7', lastDate: parse('19/09/2025', 'dd/MM/yyyy', new Date()).toISOString(), lastKm: 404995, supplier: 'CHIP TRUCK', responsible: 'Admin', km: 180000, months: 72 },
    { id: 'vs8', vehicleId: 'v1', serviceId: 's8', lastDate: parse('26/08/2025', 'dd/MM/yyyy', new Date()).toISOString(), lastKm: 400000, supplier: 'Casa das Baterias', responsible: 'Admin', km: 0, months: 3 },
    { id: 'vs9', vehicleId: 'v1', serviceId: 's10', lastDate: parse('10/06/2025', 'dd/MM/yyyy', new Date()).toISOString(), lastKm: 395000, supplier: 'JATAI EXTINTORES', responsible: 'Admin', km: 0, months: 58 },
    { id: 'vs10', vehicleId: 'v1', serviceId: 's11', lastDate: parse('20/08/2024', 'dd/MM/yyyy', new Date()).toISOString(), lastKm: 380000, supplier: 'DANIEL', responsible: 'Admin', km: 0, months: 14 },
    { id: 'vs11', vehicleId: 'v1', serviceId: 's12', lastDate: parse('24/10/2025', 'dd/MM/yyyy', new Date()).toISOString(), lastKm: 410000, supplier: 'MINOL', responsible: 'Admin', km: 0, months: 24 },
    { id: 'vs12', vehicleId: 'v1', serviceId: 's13', lastDate: parse('01/07/2024', 'dd/MM/yyyy', new Date()).toISOString(), lastKm: 370000, supplier: 'Interno', responsible: 'Admin', km: 0, months: 24 },
    { id: 'vs13', vehicleId: 'v2', serviceId: 's1', lastDate: parse('16/05/2025', 'dd/MM/yyyy', new Date()).toISOString(), lastKm: 327147, supplier: 'Interno', responsible: 'Admin', km: 20000, months: 12 },
    { id: 'vs14', vehicleId: 'v2', serviceId: 's4', lastDate: parse('11/08/2025', 'dd/MM/yyyy', new Date()).toISOString(), lastKm: 330000, supplier: 'CHIP TRUCK', responsible: 'Admin', km: 40000, months: 18 },
    { id: 'vs15', vehicleId: 'v2', serviceId: 's5', lastDate: parse('09/07/2024', 'dd/MM/yyyy', new Date()).toISOString(), lastKm: 310000, supplier: 'FERNANDO', responsible: 'Admin', km: 60000, months: 18 },
    { id: 'vs16', vehicleId: 'v2', serviceId: 's6', lastDate: parse('09/07/2024', 'dd/MM/yyyy', new Date()).toISOString(), lastKm: 310000, supplier: 'FERNANDO', responsible: 'Admin', km: 60000, months: 18 },
    { id: 'vs17', vehicleId: 'v2', serviceId: 's7', lastDate: parse('11/08/2025', 'dd/MM/yyyy', new Date()).toISOString(), lastKm: 330000, supplier: 'CHIP TRUCK', responsible: 'Admin', km: 180000, months: 72 },
    { id: 'vs18', vehicleId: 'v2', serviceId: 's9', lastDate: parse('11/09/2025', 'dd/MM/yyyy', new Date()).toISOString(), lastKm: 342078, supplier: 'DANIEL', responsible: 'Admin', km: 2500, months: 1 },
    { id: 'vs19', vehicleId: 'v2', serviceId: 's12', lastDate: parse('30/10/2025', 'dd/MM/yyyy', new Date()).toISOString(), lastKm: 345000, supplier: 'MINOL NF 15849', responsible: 'Admin', km: 0, months: 24 },
    { id: 'vs20', vehicleId: 'v2', serviceId: 's13', lastDate: parse('01/07/2024', 'dd/MM/yyyy', new Date()).toISOString(), lastKm: 310000, supplier: 'Interno', responsible: 'Admin', km: 0, months: 24 },
];
